################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
SECOUTPUTBUILDVAR := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Aplication/ESP8266 \
Aplication/encoder \
Aplication/ldr \
Aplication/led \
Aplication/request \
Aplication/ring_buffer \
Drivers/STM32F1xx_HAL_Driver/Src \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Platform/delay \
Platform/encoder_driver \
Platform/encoder_queue \
Platform/encoder_task \
Platform/esp_task \
Platform/ldr_driver \
Platform/ldr_queue \
Platform/ldr_task \
Platform/led_driver \
Platform/led_task \
Platform/status_led \
Platform/usart \
Src \
Test/Debug/Aplication/ESP8266 \
Test/Debug/Aplication/encoder \
Test/Debug/Aplication/ldr \
Test/Debug/Aplication/led \
Test/Debug/Aplication/request \
Test/Debug/Aplication/ring_buffer \
Test/Debug/Aplication_test \
Test/Debug/Test \
Test/Debug/Test/ldr_test \
Test/Debug/Test/led_test \
Test/Debug/Test/mock_obj/encoder_driver \
Test/Debug/Test/mock_obj/ldr_driver \
Test/Debug/Test/mock_obj/led_driver \
Test/Debug/Test/mock_obj/usart \
Test/Debug/cmocka \
Test/Test/ldr_test \
Test/Test/led_test \
Test/Test/mock_obj/encoder_driver \
Test/Test/mock_obj/ldr_driver \
Test/Test/mock_obj/led_driver \
Test/Test/mock_obj/usart \
Test/cmocka \
Test/ldr_test/Aplication/ESP8266 \
Test/ldr_test/Aplication/encoder \
Test/ldr_test/Aplication/ldr \
Test/ldr_test/Aplication/led \
Test/ldr_test/Aplication/request \
Test/ldr_test/Aplication/ring_buffer \
Test/ldr_test/Test/ldr_test \
Test/ldr_test/Test/led_test \
Test/ldr_test/Test/mock_obj/encoder_driver \
Test/ldr_test/Test/mock_obj/ldr_driver \
Test/ldr_test/Test/mock_obj/led_driver \
Test/ldr_test/Test/mock_obj/usart \
Test/ldr_test/cmocka \
Test/led_test/Aplication/ESP8266 \
Test/led_test/Aplication/encoder \
Test/led_test/Aplication/ldr \
Test/led_test/Aplication/led \
Test/led_test/Aplication/request \
Test/led_test/Aplication/ring_buffer \
Test/led_test/Test/ldr_test \
Test/led_test/Test/led_test \
Test/led_test/Test/mock_obj/encoder_driver \
Test/led_test/Test/mock_obj/ldr_driver \
Test/led_test/Test/mock_obj/led_driver \
Test/led_test/Test/mock_obj/usart \
Test/led_test/cmocka \

